<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curioso Mundo DIY - Introdução</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        @keyframes float {
            0%, 100% { transform: translateY(0) rotate(0deg); }
            50% { transform: translateY(-20px) rotate(5deg); }
        }
        @keyframes slowSpin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
        }
        @keyframes gentlePulse {
            0%, 100% { transform: scale(1); opacity: 0.8; }
            50% { transform: scale(1.05); opacity: 1; }
        }
        @keyframes slowSlideIn {
            from { transform: translateX(-20px); opacity: 0; }
            to { transform: translateX(0); opacity: 1; }
        }
        @keyframes slowFadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
        @keyframes colorShift {
            0% { filter: hue-rotate(0deg); }
            50% { filter: hue-rotate(10deg); }
            100% { filter: hue-rotate(0deg); }
        }
        .float-slow { animation: float 8s ease-in-out infinite; }
        .slow-spin { animation: slowSpin 30s linear infinite; }
        .gentle-pulse { animation: gentlePulse 6s ease-in-out infinite; }
        .slow-slide-in { animation: slowSlideIn 3s ease-out forwards; }
        .slow-fade-in { animation: slowFadeIn 4s ease-in forwards; }
        .color-shift { animation: colorShift 15s linear infinite; }
        .delay-1 { animation-delay: 1s; }
        .delay-2 { animation-delay: 2s; }
        .delay-3 { animation-delay: 3s; }
        .delay-4 { animation-delay: 4s; }
        .delay-5 { animation-delay: 5s; }
        .bg-gradient-diy {
            background: linear-gradient(135deg, #f6d365 0%, #fda085 50%, #a6c1ee 100%);
            animation: colorShift 30s linear infinite;
        }
    </style>
</head>
<body class="bg-gray-900 min-h-screen flex items-center justify-center overflow-hidden">
    <div class="relative w-full max-w-4xl h-96 mx-auto">
        <!-- Background elements with slow animation -->
        <div class="absolute inset-0 bg-gradient-diy rounded-3xl opacity-20"></div>
        
        <!-- Tools floating around with slow animations -->
        <i class="fas fa-hammer text-yellow-500 text-4xl absolute top-10 left-20 float-slow delay-1"></i>
        <i class="fas fa-paint-brush text-blue-500 text-4xl absolute top-32 right-32 float-slow delay-2"></i>
        <i class="fas fa-ruler-combined text-green-500 text-4xl absolute bottom-20 left-32 float-slow delay-3"></i>
        <i class="fas fa-screwdriver text-red-500 text-4xl absolute bottom-10 right-20 float-slow delay-4"></i>
        <i class="fas fa-lightbulb text-yellow-300 text-5xl absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 gentle-pulse"></i>
        
        <!-- Main content -->
        <div class="relative z-10 h-full flex flex-col items-center justify-center p-8 text-center">
            <!-- Logo with slow spin animation -->
            <div class="mb-8 relative">
                <div class="w-32 h-32 bg-gradient-to-r from-yellow-400 via-red-500 to-purple-500 rounded-full flex items-center justify-center mx-auto slow-spin">
                    <div class="w-28 h-28 bg-white rounded-full flex items-center justify-center">
                        <i class="fas fa-tools text-4xl text-purple-600 gentle-pulse"></i>
                    </div>
                </div>
            </div>
            
            <!-- Channel name with slow animation -->
            <h1 class="text-5xl font-bold mb-4 text-white slow-slide-in">
                <span class="text-yellow-400">Curioso</span> 
                <span class="text-blue-400">Mundo</span> 
                <span class="text-red-500">DIY</span>
            </h1>
            
            <!-- Tagline with slow animation -->
            <p class="text-xl text-gray-200 mb-6 slow-fade-in delay-1">
                Transformando ideias em realidade!
            </p>
            
            <!-- Call to action with slow animation -->
            <div class="flex space-x-4 slow-fade-in delay-2">
                <a href="https://www.youtube.com/@CuriosoMundoDIY" target="_blank" class="px-6 py-3 bg-red-600 hover:bg-red-700 text-white rounded-full font-semibold flex items-center transition-all transform hover:scale-105 gentle-pulse">
                    <i class="fas fa-play mr-2"></i> Assista Agora
                </a>
                <a href="https://www.youtube.com/@CuriosoMundoDIY?sub_confirmation=1" target="_blank" class="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-full font-semibold flex items-center transition-all transform hover:scale-105 gentle-pulse">
                    <i class="fas fa-bell mr-2"></i> Inscreva-se
                </a>
            </div>
            
            <!-- Social icons without animations -->
            <div class="mt-8 flex space-x-6">
                <a href="https://www.youtube.com/@CuriosoMundoDIY" target="_blank" class="text-gray-300 hover:text-white text-2xl transition-colors">
                    <i class="fab fa-youtube"></i>
                </a>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Adiciona interação suave aos botões
            const buttons = document.querySelectorAll('button, a');
            buttons.forEach(button => {
                button.addEventListener('mouseenter', () => {
                    button.classList.add('animate-pulse');
                });
                button.addEventListener('mouseleave', () => {
                    button.classList.remove('animate-pulse');
                });
            });
            
            // Efeito parallax suave para o background
            document.addEventListener('mousemove', (e) => {
                const x = e.clientX / window.innerWidth;
                const y = e.clientY / window.innerHeight;
                const bg = document.querySelector('.bg-gradient-diy');
                bg.style.transform = `translate(${x * 10}px, ${y * 10}px)`;
            });
        });
    </script>
</body>
</html>
